name: Release build

on:
  push:
    tags:
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: true
      matrix:
        build:
          - name: SSPGU-win-amd64.exe
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: SSPGU
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.23'
          wails-version: 'v2.9.3'

      - name: Checkout create-image
        uses: actions/checkout@v2
        with:
          repository: create-dmg/create-dmg
          path: ./build/create-dmg
          ref: master

      - name: Get version tag
        id: get_version_step
        shell: bash
        run: |
          if [ "${{ github.ref }}" != "" ]; then
            version=$(echo ${{ github.ref }} | sed 's#.*/.*/\(.*$\)#\1#')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          else
            version=$(echo $(date +%Y-%m-%d-%H-%M) | sed -e 's/v//g')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          fi

    #   - name: get platform tag
    #     id: get_platform
    #     if: runner.os == 'macOS'
    #     shell: bash
    #     run: |
    #       tag=$(echo "darwin-$(uname -m)")
    #       echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Package Macos
        id: Package_Macos
        if: runner.os == 'macOS'
        working-directory: ./build
        run: |
          ./create-dmg/create-dmg \
            --no-internet-enable \
            --volname "SSPGU" \
            --volicon "bin/SSPGU.app/Contents/Resources/iconfile.icns" \
            --text-size 12 \
            --window-pos 400 400 \
            --window-size 660 450 \
            --icon-size 80 \
            --icon "SSPGU.app" 180 180 \
            --hide-extension "SSPGU.app" \
            --app-drop-link 480 180 \
            "bin/SSPGU-mac-universal-${{ steps.get_version_step.outputs.version }}.dmg" \
            "bin"
          rm -rvf bin/SSPGU.app
      
      - uses: actions/upload-artifact@v4
        with:
          name: Wails Build ${{runner.os}}
          path: |
            */bin/
            *\bin\*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*